# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id_a', models.AutoField(primary_key=True, serialize=False)),
                ('motor_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Soil_Moisture_Sensor',
            fields=[
                ('id_s', models.AutoField(primary_key=True, serialize=False)),
                ('soil_value', models.CharField(max_length=250)),
                ('plant_id1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Water_body',
            fields=[
                ('id_wa', models.AutoField(primary_key=True, serialize=False)),
                ('water_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_Station',
            fields=[
                ('id_w', models.AutoField(primary_key=True, serialize=False)),
                ('tem_value', models.CharField(max_length=250)),
                ('hum_value', models.CharField(max_length=250)),
                ('rain_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='actuator',
            name='plant_id2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.Plant'),
        ),
    ]
