# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='plant_id2',
        ),
        migrations.RemoveField(
            model_name='soil_moisture_sensor',
            name='plant_id1',
        ),
        migrations.AddField(
            model_name='actuator',
            name='plant',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soil_moisture_sensor',
            name='plant',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='water_body',
            name='plant',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weather_station',
            name='plant',
            field=models.IntegerField(null=True),
        ),
    ]
