# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20171104_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_station',
            name='a_value',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather_station',
            name='b_value',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather_station',
            name='c_value',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather_station',
            name='d_value',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather_station',
            name='e_value',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather_station',
            name='f_value',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
    ]
